(()=>{const $=id=>document.getElementById(id),study=$('study'),stats=document.querySelector('main>.stats'),nav=document.querySelector('.bottom nav');if(!study||!stats||!nav)return;
const home=document.createElement('section');home.id='dashboard';home.className='section active';home.innerHTML='<h2 class="ww-dashboard-title">Learning dashboard</h2><p class="ww-lead">Your German vocabulary workspace</p><div class="ww-shortcuts"><button class="ww-shortcut" data-ww-go="study"><b>Start practice →</b><span>10-question vocabulary sessions</span></button><button class="ww-shortcut" data-ww-go="review"><b>Review mistakes →</b><span>Focus on words you missed</span></button><button class="ww-shortcut" data-ww-go="stats"><b>Learning history →</b><span>Scores and progress by session</span></button></div>';
stats.before(home);home.insertBefore(stats,home.querySelector('.ww-shortcuts'));
const dash=document.createElement('button');dash.dataset.nav='dashboard';dash.innerHTML='<b>◫</b>Dashboard';nav.prepend(dash);
const labels={dashboard:'Dashboard',study:'Practice',topics:'Topics',bank:'Vocabulary',review:'Review',stats:'History'};
for(const b of nav.querySelectorAll('[data-nav]')){const k=b.dataset.nav;b.innerHTML='<b>'+({dashboard:'◫',study:'✦',topics:'▦',bank:'⌕',review:'↻',stats:'▥'}[k]||'•')+'</b>'+labels[k]}
const heading=document.createElement('div');heading.className='ww-heading';heading.innerHTML='<div><h2 id="ww-page-title">Dashboard</h2><p id="ww-page-subtitle">Overview and recent activity</p></div>';home.parentNode.insertBefore(heading,home);
const back=document.createElement('button');back.className='btn secondary ww-back';back.textContent='← Practice settings';study.prepend(back);back.addEventListener('click',()=>{document.body.classList.remove('ww-quiz-mode');window.scrollTo(0,0)});
const titles={dashboard:['Dashboard','Overview and recent activity'],study:['Practice','Personalized vocabulary sessions'],topics:['Topics','Explore the learning roadmap'],bank:['Vocabulary','Search your German word bank'],review:['Review','Words you answered incorrectly'],stats:['History','Your learning performance']};
function activate(page){const title=titles[page];if(!title)return;for(const s of document.querySelectorAll('.section'))s.classList.toggle('active',s.id===page);for(const b of document.querySelectorAll('[data-nav]'))b.classList.toggle('active',b.dataset.nav===page);$('ww-page-title').textContent=title[0];$('ww-page-subtitle').textContent=title[1];if(page==='study')document.body.classList.remove('ww-quiz-mode');window.scrollTo(0,0)}
document.addEventListener('click',e=>{const quick=e.target.closest('[data-ww-go]');if(quick){const page=quick.dataset.wwGo;document.querySelector('.bottom [data-nav="'+page+'"]')?.click();activate(page);return}const b=e.target.closest('[data-nav]');if(b){const page=b.dataset.nav;queueMicrotask(()=>activate(page));return}const quizButton=e.target.closest('#startQuiz,#startReview,#reviewNow,#reviewAll,#practiceBank,#nextQuiz,#reviewMistakes');if(quizButton){document.body.classList.add('ww-quiz-mode');queueMicrotask(()=>{activate('study');document.body.classList.add('ww-quiz-mode')})}},true);
dash.addEventListener('click',()=>activate('dashboard'));
const observer=new MutationObserver(()=>{if($('quizStage')?.querySelector('#nextQuiz'))document.body.classList.add('ww-quiz-mode')});observer.observe($('quizStage'),{childList:true});
activate('dashboard');
})();
