import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../../',import.meta.url);
const read=name=>readFileSync(new URL(name,root),'utf8');
const html=read('index.html');
const css=read('settings.css');
const account=read('account.css');
const native=read('mobile/src/account.js');
const gradle=read('mobile/android/app/build.gradle');
const pack=JSON.parse(read('content/v1/pack.json'));
const live=read('live-content.js');
const settings=read('settings.js');
const prepare=read('mobile/scripts/prepare.mjs');
assert.match(html,/settings\.css/, 'Both native and web must load the shared stylesheet');
assert.match(css,/Unified, surface-light UI/, 'The app-wide flat design system must be present');
assert.match(css,/\.card,.stat,.ww-shortcut/, 'All primary content surfaces must use the same canvas');
assert.match(css,/\.choice\.good/, 'Correct-answer feedback must remain visible');
assert.match(css,/\.choice\.bad/, 'Incorrect-answer feedback must remain visible');
assert.match(css,/html\[data-mode=dark\]/, 'Dark mode must remain supported');
assert.match(account,/\.ww-welcome-content\{[^}]*background:transparent/, 'Welcome must have no surrounding card');
assert.match(native,/ww-welcome-google/, 'Google sign-in option is present');
assert.match(native,/ww-welcome-guest/, 'Guest option is present');
assert.match(native,/ww-welcome-status/, 'Sign-in problems remain visible on the first screen');
assert.match(native,/switchProfile\(account\?\.uid\|\|'guest'\)/, 'Guest and Google learning histories remain separate');
assert.match(gradle,/WORTWEG_CI_KEYSTORE/, 'CI preview signing must use an explicit keystore');
assert.equal(pack.schema,1,'Live content schema must be supported');
assert.ok(pack.lessons.length>0,'APK must ship usable starter lessons');
assert.ok(prepare.includes('live-content.js'),'Native bundle includes live updater');
assert.match(prepare,/['"]content['"]/,'Native bundle includes offline word pack');
assert.ok(settings.includes('live-content.js'),'Website and APK load the same local updater');
assert.match(live,/credentials:'omit'/,'Public vocabulary downloads never send user credentials');
assert.match(live,/textContent/,'Remote content is rendered as text rather than executable HTML');
const styles=[...html.matchAll(/<link\b[^>]+>/g)].map(m=>m[0]).filter(s=>/stylesheet/i.test(s));
console.log('PASS: unified no-card layout, contrast states, sign-in choices, dark mode and isolated profiles.');
console.log('Web stylesheet links:',styles.map(s=>s.slice(0,160)).join(' | '));
